### ISSUE TITLE
story player

### ISSUE THREAD

**Issue by farfromrefug** [o-daneel/Lunii.QT#12]
Great software! Do you know of any "player" which could read pk files from linux/macos/windows?
Looking at a way to play stories outside of Lunii

**Comment by mpecheux** [comment]
There is one on Windows called WINLunii, can be download here : 
 https://mega.nz/file/5D9WWQ5Q#LkVygzn2xkxasMfre9Qy-iAWQMDD83iYT0Q-7DSyq8w

you can find more info on french discord : https://monurl.ca/lunii.creations

**Comment by farfromrefug** [comment]
@mpecheux awesome thanks a lot for the link. I am on the discord now!
