### ISSUE TITLE
MacOS exec format error

### ISSUE THREAD

**Issue by Zeddekah** [o-daneel/Lunii.QT#14]
Hello, I run it on a Mac Mini M2 and when terminal open :

```
Last login: Sat Nov 23 01:16:29 on ttys000
/Users/xxx/Downloads/lunii-qt ; exit;
xxx@Mac-mini-xxx ~ % /Users/xxx/Downloads/lunii-qt ; exit;
zsh: exec format error: /Users/xxx/Downloads/lunii-qt

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Opération terminée]
```

**Comment by o-daneel** [comment]
@Zeddekah I think that the prebuilt Mac version is not compatible with your version.
You can still build it by yourself by following the README.
Your arch is not available for free in Github. Thus I can automate this version
